# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import epidemic_replication_pb2 as epidemic__replication__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in epidemic_replication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.processTransaction = channel.unary_unary(
                '/NodeService/processTransaction',
                request_serializer=epidemic__replication__pb2.TransactionRequest.SerializeToString,
                response_deserializer=epidemic__replication__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.nodeUpdate = channel.unary_unary(
                '/NodeService/nodeUpdate',
                request_serializer=epidemic__replication__pb2.NodeData.SerializeToString,
                response_deserializer=epidemic__replication__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.nodeGetData = channel.unary_unary(
                '/NodeService/nodeGetData',
                request_serializer=epidemic__replication__pb2.Empty.SerializeToString,
                response_deserializer=epidemic__replication__pb2.NodeData.FromString,
                _registered_method=True)


class NodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def processTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def nodeUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def nodeGetData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'processTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.processTransaction,
                    request_deserializer=epidemic__replication__pb2.TransactionRequest.FromString,
                    response_serializer=epidemic__replication__pb2.TransactionResponse.SerializeToString,
            ),
            'nodeUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.nodeUpdate,
                    request_deserializer=epidemic__replication__pb2.NodeData.FromString,
                    response_serializer=epidemic__replication__pb2.StatusResponse.SerializeToString,
            ),
            'nodeGetData': grpc.unary_unary_rpc_method_handler(
                    servicer.nodeGetData,
                    request_deserializer=epidemic__replication__pb2.Empty.FromString,
                    response_serializer=epidemic__replication__pb2.NodeData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('NodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def processTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/NodeService/processTransaction',
            epidemic__replication__pb2.TransactionRequest.SerializeToString,
            epidemic__replication__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def nodeUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/NodeService/nodeUpdate',
            epidemic__replication__pb2.NodeData.SerializeToString,
            epidemic__replication__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def nodeGetData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/NodeService/nodeGetData',
            epidemic__replication__pb2.Empty.SerializeToString,
            epidemic__replication__pb2.NodeData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
