# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: epidemic_replication.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'epidemic_replication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x65pidemic_replication.proto\")\n\x12TransactionRequest\x12\x13\n\x0btransaction\x18\x01 \x01(\t\"5\n\x13TransactionResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t\".\n\x0eNodeDataUpdate\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"8\n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x16\n\x0estatus_message\x18\x02 \x01(\t2~\n\x0bNodeService\x12?\n\x12processTransaction\x12\x13.TransactionRequest\x1a\x14.TransactionResponse\x12.\n\nnodeUpdate\x12\x0f.NodeDataUpdate\x1a\x0f.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'epidemic_replication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONREQUEST']._serialized_start=30
  _globals['_TRANSACTIONREQUEST']._serialized_end=71
  _globals['_TRANSACTIONRESPONSE']._serialized_start=73
  _globals['_TRANSACTIONRESPONSE']._serialized_end=126
  _globals['_NODEDATAUPDATE']._serialized_start=128
  _globals['_NODEDATAUPDATE']._serialized_end=174
  _globals['_STATUSRESPONSE']._serialized_start=176
  _globals['_STATUSRESPONSE']._serialized_end=232
  _globals['_NODESERVICE']._serialized_start=234
  _globals['_NODESERVICE']._serialized_end=360
# @@protoc_insertion_point(module_scope)
